dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint

jobs:
  include:
    - stage: lint
      name: Shellcheck Verification
      install:
        - make shellcheck/install
      script:
        - make sh/lint
    - stage: lint
      name: Terraform Lint/Format Verification
      install:
        - make terraform/install
        - make terraform-docs/install
      script:
        - make terraform/lint
        - make docs/lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/tfdocs-awk
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [TFDOCS-AWK v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/tfdocs-awk/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: TOKEN_PLACEHOLDER
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/tfdocs-awk
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
