dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint

jobs:
  include:
    - stage: lint
      name: Shellcheck Verification
      install:
        - make shellcheck/install
      script:
        - make sh/lint
