dist: xenial

language: node_js

node_js:
  - "8"

stages:
  - lint

jobs:
  include:
    - stage: lint
      name: Shellcheck Verification
      install:
        - make shellcheck/install
      script:
        - make sh/lint
    - stage: lint
      name: Terraform Lint/Format Verification
      install:
        - make terraform/install
        - make terraform-docs/install
      script:
        - make terraform/lint
        - make docs/lint
    - stage: deploy
      if: branch = master AND type = push AND repo = plus3it/tfdocs-awk
      before_script:
        - |
          PRIOR_VERSION=$(git describe --abbrev=0 --tags)
          RELEASE_VERSION=$(grep current_version $TRAVIS_BUILD_DIR/.bumpversion.cfg | sed 's/^.*= //' )
          RELEASE_BODY="* [TFDOCS-AWK v$RELEASE_VERSION CHANGELOG](https://github.com/plus3it/tfdocs-awk/blob/$RELEASE_VERSION/CHANGELOG.md)"
          export PRIOR_VERSION RELEASE_VERSION RELEASE_BODY
      script: skip
      before_deploy:
        - |
          (set -x; git tag -a $RELEASE_VERSION -m $RELEASE_VERSION)
      deploy:
        provider: releases
        api_key:
          secure: nomCp3QqGRZhTD03Xj7d03RdW13lAlNegzcZ7buikosYWPk0vkPtZvCtfCFVE4gwa6EsoKmjGl7PeQflD0+BI/RCx8iUFERSOesgk+zazTZr8w+uYSJfvnBUZnk+BrNB0LzkjU9AP+dD02wx4srlFqUcyd5MIaHH1lkItZgZ/fL+goFo8C82NOY9fUEyLdjgMHTNaY7tw0cY8DWDZsGqektRofqubfrJoM3gDB3wMnwQD7xqWA7428LJD9iWbZG2KsSUrojE8DkhRslWzH8yEUae+Ir4dwOmHkR/zrpQD1Tj1M/Y6twjBK9eIdPHACatNN5BWEPtksDm1dqP6g4RhBn7j4ArnqNqcHaZaV/0wRR7uPwVUHxQ2/Cb2QHDOqCjH0sNxmyi9m48LQ3qS1GnG0G1ZJK+z0E9SrKwvJhYthX4kxCmeO6QewUI0tXP6Yo/fvQnnvL7RFLfoYf8txIdNP2KmjGipinezTk1Yv6R32Si1PQFcqPc4NMr0y/iJXXoGZqqw4fOfWiLOwQW9mtw3nmRoKpPqQqzEXTh8y21kL42VaHh7TrdY+3aPlnJC27GBpo7psADr//y7ITxlwh0aSlRtVkioepgg0hKdumTO+I+doVJFUC49WXn4Jg1zQWkCvKsK9CylgZO+2tROsv3l73zEm9/ZrSqex3PcZbId1E=
        name: $RELEASE_VERSION
        body: $RELEASE_BODY
        tag_name: $RELEASE_VERSION
        target_commitish: $TRAVIS_COMMIT
        draft: false
        on:
          branch: master
          repo: plus3it/tfdocs-awk
          condition: '"$PRIOR_VERSION" != "$RELEASE_VERSION"'
